language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose --all --all-targets
  - cargo test --verbose --all
  - cargo build --release --verbose --all --all-targets
  - cargo test --release --verbose --all
os:
  - linux
  - osx
