[package]
name = "log4rs-syslog"
description = "Syslog appender for log4rs based on libc's syslog() function (*nix only)"
version = "1.0.4"
authors = ["Ivan Mironov <mironov.ivan@gmail.com>"]
license = "MIT/Apache-2.0"
keywords = ["logger", "log", "logging", "nix", "syslog"]
categories = ["os::unix-apis"]
publish = true
repository = "https://github.com/im-0/log4rs-syslog"
documentation = "https://github.com/im-0/log4rs-syslog"
readme = "README.md"
build = "build.rs"

[badges]
travis-ci = { repository = "im-0/log4rs-syslog", branch = "b1.0.0" }

[features]
default = ["file"]
file = ["log4rs/file", "serde", "serde_derive"]
unstable = []

[dependencies]
bitflags = { version = "0.9", default_features = false }
lazy_static = { version = "0.2", default_features = false }
libc = { version = "0.2", default_features = false }
log = { version = "0.3", default_features = false }
log4rs = { version = "0.7", default_features = false }
serde = { version = "1.0", default_features = false, optional = true }
serde_derive = { version = "1.0", default_features = false, optional = true }

[build-dependencies]
skeptic = "0.13"

[dev-dependencies]
log4rs = "0.7"
tempfile = "2.1"
skeptic = "0.13"
